### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": -10000000
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
"userId": 2,
"accountNumber": "1000000003"
}

### get accounts
GET http://localhost:8080/account?user-id=1
Content-Type: application/json